language: go

go:
  - "1.11.x"

env:
  global:
    - LINUX_BINARY_PATH: ${GOPATH}/bin/terraform-provider-rollbar
    - DARWIN_BINARY_PATH: ${GOPATH}/bin/darwin_amd64/terraform-provider-rollbar

script:
  - make vet
  - make test

# Build and zip the binaries.
before_deploy:
  - GIT_TAG=$(git describe --tags)
  - make build
  - mv ${LINUX_BINARY_PATH} ${LINUX_BINARY_PATH}_${GIT_TAG}
  - zip -j ${LINUX_BINARY_PATH}_${GIT_TAG}_linux_amd64.zip ${LINUX_BINARY_PATH}_${GIT_TAG}
  - make build-darwin
  - mv ${DARWIN_BINARY_PATH} ${DARWIN_BINARY_PATH}_${GIT_TAG}
  - zip -j ${DARWIN_BINARY_PATH}_${GIT_TAG}_darwin_amd64.zip ${DARWIN_BINARY_PATH}_${GIT_TAG}

# Deploy only when a tag is created and pushed to the master branch.
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - ${LINUX_BINARY_PATH}_${GIT_TAG}_linux_amd64.zip
    - ${DARWIN_BINARY_PATH}_${GIT_TAG}_darwin_amd64.zip
  skip_cleanup: true
  file_glob: "true"
  on:
    branch: "master"
    tags: true
  condition: ${GIT_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]$
